=== maikerosa/exampleXML-DTD/XML & DTD/1/agenda.dtd
<!ELEMENT agenda (inicialA, inicialB)>
<!ELEMENT inicialA (contato*)>
<!ATTLIST inicialA letra CDATA #REQUIRED>
<!ATTLIST inicialB letra CDATA #REQUIRED>
<!ELEMENT inicialB (contato*)>
<!ELEMENT contato (nome, telefone+, endereco, email, msn, skype, tipocontato+)>
<!ATTLIST contato id CDATA #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT telefone (#PCDATA)>
<!ATTLIST telefone tipo CDATA #REQUIRED>
<!ELEMENT endereco (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT msn (#PCDATA)>
<!ELEMENT skype (#PCDATA)>
<!ELEMENT tipocontato (#PCDATA)>
<!ATTLIST tipocontato tipo CDATA #REQUIRED>

=== maikerosa/exampleXML-DTD/XML & DTD/1/agenda.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">


<agenda>

    <!-- Contatos com Inicial A-->
    <inicialA letra="A">

        <!-- Contato 1-->
        <contato id="CT01">
            <nome> Amauri  Adelino da Silva</nome>
            <telefone tipo="res.">000-000-000</telefone>
            <telefone tipo="trab.">000-000-000</telefone>
            <telefone tipo="cel.">000-000-000</telefone>
            <endereco>Rua Perto do Riacho </endereco>
            <email>ExemploDeEmail@gmail.com</email>
            <msn>Jose.S</msn>
            <skype>Jose.S</skype>
            <tipocontato tipo="pessoal " />
        </contato>

        <!-- Contato 2-->
        <contato id="CT02">
            <nome> Amanda da Silva</nome>
            <telefone tipo="res.">000-000-000</telefone>
            <telefone tipo="trab.">000-000-000</telefone>
            <telefone tipo="cel.">000-000-000</telefone>
            <endereco>Rua Perto do Riacho </endereco>
            <email>ExemploDeEmail2@gmail.com</email>
            <msn>Amanda.S</msn>
            <skype>Amanda.S</skype>
            <tipocontato tipo="comercial" />
        </contato>
    </inicialA>

    <!-- Contatos com Inicial B-->
    <inicialB letra="B">

        <!-- Contato 1-->
        <contato id="CT03">
            <nome> Bamacedo  Rocha da Silva</nome>
            <telefone tipo="res.">000-000-000</telefone>
            <telefone tipo="trab.">000-000-000</telefone>
            <telefone tipo="cel.">000-000-000</telefone>
            <endereco>Rua Perto do Riacho </endereco>
            <email>ExemploDeEmail3@gmail.com</email>
            <msn>Bamacedo.S</msn>
            <skype>Bamacedo.S</skype>
            <tipocontato tipo="pessoal " />
        </contato>
    </inicialB>
</agenda>
